# .scrutinizer.yml
build:
  nodes:
    analysis:
      environment:
        php:
          version: 7.4
      project_setup:
        override: true
      tests:
        override:
          - php-scrutinizer-run

    php74:
      environment:
        php: 7.4

    php80:
      environment:
        php: 8.0

    php81:
      environment:
        php: 8.1

    php82:
      environment:
        php: 8.2

    php83:
      environment:
        php: 8.3

    php84:
      environment:
        php: 8.4

filter:
  excluded_paths:
    - '_archive/*'
    - 'tests/*'
tools:
  external_code_coverage:
    timeout: 300    # Timeout in seconds.
