name: CI

on: [push, pull_request]

jobs:
  phpunit-tests:
    strategy:
      fail-fast: false
      matrix:
        php_version: ["8.1", "8.2", "8.3"]
        phpunit_version: ["9.6", "10.5", "11.2"]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          coverage: xdebug
      - uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php_version }}
      - run: composer install --prefer-dist --no-interaction --no-suggest
      - name: Unit Tests
        run: vendor/bin/phpunit --stderr
