name: CI

on: [push, pull_request]

jobs:
  phpunit-tests:
    strategy:
      fail-fast: false
      matrix:
        php_version: ["8.1", "8.2", "8.3"]
        phpunit_version: ["9.6", "10.5", "11.2"]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          coverage: xdebug

      # Step to copy composer.dist.json to composer.json
      - name: Prepare composer.json
        run: cp htdocs/class/libraries/composer.dist.json htdocs/class/libraries/composer.json

      # Install dependencies in the correct directory
      - uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php_version }}
          working_dir: htdocs/class/libraries

      - name: Install Dependencies
        working-directory: htdocs/class/libraries
        run: composer install --prefer-dist --no-interaction --no-suggest

      # Run unit tests from the correct directory
      - name: Unit Tests
        working-directory: htdocs/class/libraries
        run: vendor/bin/phpunit --stderr
